// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZ90Yk8XmRT3QlZLxrXtPaGkEqehXS6o',
    appId: '1:668110973429:web:e500519ad9d6e2c24558bc',
    messagingSenderId: '668110973429',
    projectId: 'shebaone-b63d7',
    authDomain: 'shebaone-b63d7.firebaseapp.com',
    storageBucket: 'shebaone-b63d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Lh_Fe46s3MK3T8Cm91dyptK-GogCHEs',
    appId: '1:668110973429:android:75814c1c11587ed44558bc',
    messagingSenderId: '668110973429',
    projectId: 'shebaone-b63d7',
    storageBucket: 'shebaone-b63d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSyQJ_5upVlbhWbdmwArozr8gaqornPw',
    appId: '1:668110973429:ios:d0341605cca9fb124558bc',
    messagingSenderId: '668110973429',
    projectId: 'shebaone-b63d7',
    storageBucket: 'shebaone-b63d7.appspot.com',
    iosClientId: '668110973429-qpoq6f6lltf36h30tfboj3r5dt53fuka.apps.googleusercontent.com',
    iosBundleId: 'com.wiztecbd.shebaone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSyQJ_5upVlbhWbdmwArozr8gaqornPw',
    appId: '1:668110973429:ios:a20cc6234d4890654558bc',
    messagingSenderId: '668110973429',
    projectId: 'shebaone-b63d7',
    storageBucket: 'shebaone-b63d7.appspot.com',
    iosClientId: '668110973429-d2lbijktt57hr6mpunnbthn3c2f562qj.apps.googleusercontent.com',
    iosBundleId: 'com.wiztecbd.shebaone.RunnerTests',
  );
}
